/// Flutter icons CoffeeIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CoffeeIcons
///      fonts:
///       - asset: fonts/CoffeeIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CoffeeIcons {
  CoffeeIcons._();

  static const _kFontFam = 'CoffeeIcons';
  static const String? _kFontPkg = null;

  static const IconData cup_medium = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup_small = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jamaica_flower = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData locate = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData profile = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar_cube_one = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar_cube_three = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar_cube_two = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sugar_not_sugar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xeba4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cream = IconData(0xeba5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cup_large = IconData(0xeba6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
